[project]
name = "beer-agenda"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "crawl4ai>=0.7.8",
]

[dependency-groups]
dev = [
  "commitizen>=4.11.0",
  "pre-commit>=4.5.1",
]

[tool.commitizen]
name = "cz_conventional_commits"
